name: Práctica final Joan González Albert 2DAW

on:
  push:
    branches: [ main ]

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  cypress_job:
    runs-on: ubuntu-latest
    needs: linter_job
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Cypress Run
        uses: cypress-io/github-action@v5
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        continue-on-error: true
        id: cypressTests
      - name: Resultado en - result.txt
        run: echo ${{ steps.cypressTests.outcome }} > result.txt
      - name: Upload Artifact Result
        uses: actions/upload-artifact@v3
        with:
          name: test_result
          path: result.txt
