name: Práctica final Joan González Albert 2DAW

on:
  push:
    branches: [ main ]

jobs:
  linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout lint
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint